Discord.js upgrade
stt-datacore/bot pull request #59
Opened 2023-10-07 01:15 UTC by nmoschkin

Refactored to use the upgraded Discord.js libs.

2023-10-09 22:59 UTC, silasary requested changes

2023-10-09 22:59 UTC, silasary commented on src/utils/discord.ts
> +		if (message.guild && (!message.guild.roles.everyone.permissionsIn(message.channel! as NonThreadGuildBasedChannel).has('UseExternalEmojis') || !message.guild?.members.me?.premiumSince)) {
Bots always have external emoji permissions, but technically don't have nitro. This check will break things

2023-10-10 01:09 UTC, nmoschkin commented on src/utils/discord.ts
> +		if (message.guild && (!message.guild.roles.everyone.permissionsIn(message.channel! as NonThreadGuildBasedChannel).has('UseExternalEmojis') || !message.guild?.members.me?.premiumSince)) {
This was the only way that I could get emojis to show up. It would appear that the bot does not have those permissions?

2023-10-10 01:13 UTC, nmoschkin commented on src/utils/discord.ts
> +		if (message.guild && (!message.guild.roles.everyone.permissionsIn(message.channel! as NonThreadGuildBasedChannel).has('UseExternalEmojis') || !message.guild?.members.me?.premiumSince)) {
I will double back and look at permissions to confirm. But I have the external emojis on, in my server...

2023-10-29 05:09 UTC, silasary approved these changes
Ship it 😁

2023-10-29 11:24 UTC, merged